name: CI Pushes

on: [push, pull_request]

jobs:
  Doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_genalyzer.sh

      - name: Build doc
        run: |
          cd doc && make html
          cd ..