name: CI Pushes

on: [push, pull_request]

jobs:
  UbuntuDoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_genalyzer.sh

  UbuntuDeploy:
    runs-on: ubuntu-latest
    needs: [Doc]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_genalyzer.sh
          pwd
          ls
          ls -la build/
          ls -la build/doc
          ls -la build/doc/sphinx	  
      - name: Publish doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/sphinx

  MacOSDoc:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          brew install cmake tar bzip2 gzip build-essential libfftw3-dev python3-sphinx doxygen
	  pip3 install breathe sphinx_rtd_theme
	  mkdir -p build
	  cd build
	  cmake ..
	  sudo make -j4
	  sudo make test
	  sudo make install
	  sudo ldconfig
	  cd ..